# Generated by Django 5.0.1 on 2024-01-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models

from ..models import Profile


def populate_user_table(apps, schema_editor):
    user1 = User(
        is_superuser=True, is_staff=True, username="admin", email="admin@email.com"
    )
    user1.save()

    user2 = User(
        username="4meRomance",
        email="coemperor@famemma.net",
        last_name="Rodriguez",
        first_name="John",
    )
    user2.save()

    user3 = User(
        username="AirWow",
        email="flocation.vam4@glendenningflowerdesign.com",
        last_name="Paul",
        first_name="Ada",
    )
    user3.save()

    user4 = User(
        username="DavWin",
        email="5houssam.kessaiso@facpidif.ml",
        last_name="Grahm",
        first_name="Cassandra",
    )
    user4.save()

    user5 = User(
        username="HeadlinesGazer",
        email="jssssss33@acee9.live",
        last_name="Lal",
        first_name="Jamie",
    )
    user5.save()


def populate_profile_table(apps, schema_editor):
    profile1 = Profile(favorite_city="Buenos Aires", user=User.objects.get(id=5))
    profile1.save()

    profile2 = Profile(favorite_city="Barcelona", user=User.objects.get(id=4))
    profile2.save()

    profile3 = Profile(favorite_city="Budapest", user=User.objects.get(id=3))
    profile3.save()

    profile4 = Profile(favorite_city="Berlin", user=User.objects.get(id=2))
    profile4.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorite_city", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_user_table),
        migrations.RunPython(populate_profile_table),
    ]
