# Generated by Django 5.0.1 on 2024-01-16 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from ..models import Address, Letting


def populate_address_table(apps, schema_editor):
    address1 = Address(
        number=7217,
        street="Bedford Street",
        city="Brunswick",
        state="GA",
        zip_code=31525,
        country_iso_code="USA",
    )
    address1.save()

    address2 = Address(
        number=4,
        street="Military Street",
        city="Willoughby",
        state="OH",
        zip_code=44094,
        country_iso_code="USA",
    )
    address2.save()

    address3 = Address(
        number=340,
        street="Wintergreen Avenue",
        city="Newport News",
        state="VA",
        zip_code=23601,
        country_iso_code="USA",
    )
    address3.save()

    address4 = Address(
        number=9230,
        street="E. Joy Ridge Street",
        city="Marquette",
        state="MI",
        zip_code=49855,
        country_iso_code="USA",
    )
    address4.save()

    address5 = Address(
        number=9606,
        street="Harvard Street",
        city="Aliquippa",
        state="PA",
        zip_code=15001,
        country_iso_code="USA",
    )
    address5.save()

    address6 = Address(
        number=588,
        street="Argyle Avenue",
        city="East Meadow",
        state="NY",
        zip_code=11554,
        country_iso_code="USA",
    )
    address6.save()


def populate_letting_table(apps, schema_editor):
    letting1 = Letting(
        title="Joshua Tree Green Haus /w Hot Tub", address=Address.objects.get(id=1)
    )
    letting1.save()

    letting2 = Letting(title="Oceanview Retreat", address=Address.objects.get(id=2))
    letting2.save()

    letting3 = Letting(title="'Silo Studio' Cottage", address=Address.objects.get(id=3))
    letting3.save()

    letting4 = Letting(
        title="Pirates of the Caribbean Getaway", address=Address.objects.get(id=4)
    )
    letting4.save()

    letting5 = Letting(
        title="The Mushroom Dome Retreat & LAND of Paradise Suite",
        address=Address.objects.get(id=5),
    )
    letting5.save()

    letting5 = Letting(
        title="Underground Hygge",
        address=Address.objects.get(id=6),
    )
    letting5.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            options={"verbose_name_plural": "Addresses"},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(9999)]
                    ),
                ),
                ("street", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        max_length=2,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "zip_code",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999)]
                    ),
                ),
                (
                    "country_iso_code",
                    models.CharField(
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Letting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lettings.address",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_address_table),
        migrations.RunPython(populate_letting_table),
    ]
